//----------------------------------------------------------------------------
// gem_axis_sva -- AXI-Stream protocol legality, bound to both user ports.
//
// A test checks a scenario you constructed. An assertion checks an invariant
// during EVERY scenario, including the ones nobody thought to write. These
// five properties hold on every cycle of every regression run, which means the
// random sweeps are checking protocol legality for free.
//
// Bound rather than instantiated, so no property language ever appears in
// synthesisable code (fpga_project_flow.md Stage 3). The bind statements live
// at the bottom of this file, which also makes them one place to look when
// asking "what is actually being checked".
//
// These are also the interface contract in executable form. When Stage 5
// connects a module that deasserts tvalid mid-transfer because its author read
// the handshake differently, this fires at the exact cycle it happens rather
// than surfacing as corrupted output forty thousand cycles later.
//----------------------------------------------------------------------------

`ifndef GEM_AXIS_SVA_SV
`define GEM_AXIS_SVA_SV

`timescale 1ns / 1ps

module gem_axis_sva #(
    parameter string PORT_NAME = "axis",
    parameter int    USER_WIDTH = 1
) (
    input wire                    clk,
    input wire                    rst_n,
    input wire [7:0]              tdata,
    input wire                    tvalid,
    input wire                    tready,
    input wire                    tlast,
    input wire [USER_WIDTH-1:0]   tuser
);

    // Every property is guarded against reset: a port is allowed to be
    // anything while held in reset, and asserting otherwise produces the
    // classic wall of startup failures that trains people to ignore assertion
    // output entirely.
    //
    // The guard is repeated per property rather than written once as
    // `default disable iff (!rst_n)`, which XSim 2024.2 rejects outright:
    // "the SystemVerilog feature Default Disable iff declaration is not
    // supported yet for simulation". Same meaning, more typing.

    // 1. Once offered, a beat stays offered. A master that withdraws tvalid
    //    because it changed its mind has broken the handshake, and the symptom
    //    downstream is a dropped byte with no other trace.
    a_tvalid_held: assert property (@(posedge clk) disable iff (!rst_n)
        (tvalid && !tready) |=> tvalid)
        else $error("%s: tvalid deasserted before tready -- beat withdrawn", PORT_NAME);

    // 2. The payload of a stalled beat cannot change underneath the receiver.
    a_tdata_stable: assert property (@(posedge clk) disable iff (!rst_n)
        (tvalid && !tready) |=> $stable(tdata))
        else $error("%s: tdata changed while the beat was stalled", PORT_NAME);

    a_tlast_stable: assert property (@(posedge clk) disable iff (!rst_n)
        (tvalid && !tready) |=> $stable(tlast))
        else $error("%s: tlast changed while the beat was stalled", PORT_NAME);

    // 3. tuser is a per-frame sideband, so it must also survive a stall.
    a_tuser_stable: assert property (@(posedge clk) disable iff (!rst_n)
        (tvalid && !tready) |=> $stable(tuser))
        else $error("%s: tuser changed while the beat was stalled", PORT_NAME);

    // 4. tlast is meaningless without a beat to end. This catches an end-of-
    //    frame pulse generated by a frame counter rather than by the datapath,
    //    which is a real and easy mistake.
    a_tlast_needs_tvalid: assert property (@(posedge clk) disable iff (!rst_n)
        tlast |-> tvalid)
        else $error("%s: tlast asserted without tvalid", PORT_NAME);

    // 5. Nothing may be driven X once out of reset. X propagation reads
    //    exactly like a wrong value in a log file and is not the same thing.
    a_no_x: assert property (@(posedge clk) disable iff (!rst_n)
        tvalid |-> !$isunknown({tdata, tlast, tuser}))
        else $error("%s: X or Z on the data path during a valid beat", PORT_NAME);

    // 6. The handshake signals themselves must be known.
    //
    //    Property 5 checks the payload *given* tvalid, which leaves the two
    //    signals that decide whether anything happens at all unchecked. An X on
    //    tvalid is the nastiest version: every property above becomes ambiguous,
    //    and a scoreboard qualifying on (tvalid && tready) silently counts zero
    //    beats -- so the failure reports as "the design delivered nothing",
    //    which sends you looking at the datapath instead of at an
    //    uninitialised register.
    a_tvalid_known: assert property (@(posedge clk) disable iff (!rst_n)
        !$isunknown(tvalid))
        else $error("%s: tvalid is X or Z -- every handshake check below is now meaningless", PORT_NAME);

    a_tready_known: assert property (@(posedge clk) disable iff (!rst_n)
        !$isunknown(tready))
        else $error("%s: tready is X or Z", PORT_NAME);

    //------------------------------------------------------------------
    // Vacuity, measured rather than assumed
    //------------------------------------------------------------------
    //
    // Properties 1-4 are all gated on (tvalid && !tready). If that never
    // happens, all four pass without ever examining anything -- and a green
    // assertion nobody knows is vacuous reads as coverage it does not have.
    //
    // That is the current state on the rx_axis bind: R18's no-stall user
    // contract is what B.3a's 64-entry FIFO derivation assumes, so every
    // testbench ties rx_axis_tready high and the stall properties can never
    // fire. That is correct behaviour, not a bug to fix by inventing stalls
    // the spec says will not occur. What was wrong was that nothing said so.
    //
    // So count the antecedent and report at the end of simulation. A run that
    // never exercised a property now says which one, instead of quietly
    // counting it as passed.
    int n_stalled_beats = 0;
    int n_beats         = 0;

    // Counted in a plain always block, not in a cover property's action block.
    // XSim 2024.2 accepts `cover property (...) stmt;` and then does not run
    // stmt, so the counters stayed at zero and the report claimed every run was
    // vacuous -- including runs that were not. A vacuity report that is itself
    // silently broken is worse than no report, so this uses the mechanism that
    // demonstrably executes.
    always @(posedge clk) begin
        if (rst_n && !$isunknown(tvalid) && !$isunknown(tready)) begin
            if (tvalid &&  tready) n_beats++;
            if (tvalid && !tready) n_stalled_beats++;
        end
    end

    // The cover statements stay, for coverage tools and formal runs that do
    // honour them. Nothing in this file depends on them.
    c_beat_exercised:  cover property (@(posedge clk) disable iff (!rst_n)
        (tvalid && tready));
    c_stall_exercised: cover property (@(posedge clk) disable iff (!rst_n)
        (tvalid && !tready));

    final begin
        if (n_beats == 0) begin
            $display("[gem_tb] SVA %s: no beats occurred -- every property on this port was vacuous",
                     PORT_NAME);
        end else if (n_stalled_beats == 0) begin
            $display("[gem_tb] SVA %s: %0d beats, 0 stalled -- the four stall properties were vacuous (expected on rx_axis, see R18)",
                     PORT_NAME, n_beats);
        end else begin
            $display("[gem_tb] SVA %s: %0d beats, %0d stalled -- stall properties exercised",
                     PORT_NAME, n_beats, n_stalled_beats);
        end
    end

endmodule


//----------------------------------------------------------------------------
// Binds. Both user ports of gem_mac get the same contract -- which is the
// point of using a standard interface in the first place.
//
// WHAT EACH BIND ACTUALLY WATCHES, because the two are not symmetric and it
// matters when reading a green result:
//
//   tx_axis -- the *user* drives tdata/tvalid/tlast/tuser and the MAC drives
//              only tready. So properties 1-5 here constrain the testbench
//              driver, not the design. That is still worth having (a driver
//              that withdraws a beat would corrupt every TX scenario and look
//              like an RTL bug) but it is not design verification, and
//              a_tready_known is the only property on this bind that watches
//              the MAC at all.
//
//   rx_axis -- the MAC drives tdata/tvalid/tlast/tuser and the testbench
//              drives tready. Here properties 1-5 do constrain the design.
//
// Combined with the vacuity note inside the module: of the twelve property
// instances, the ones that constrain the design under the current no-stall
// contract are a_tlast_needs_tvalid, a_no_x, a_tvalid_known and a_tready_known
// on rx_axis, plus a_tready_known on tx_axis. The stall properties become live
// on rx_axis the moment R18's contract is relaxed, and the final block above
// reports whether they ran.
//----------------------------------------------------------------------------

bind gem_mac gem_axis_sva #(
    .PORT_NAME  ("tx_axis"),
    .USER_WIDTH (112)
) u_tx_axis_sva (
    .clk    (tx_clk),
    .rst_n  (tx_rst_n),
    .tdata  (tx_axis_tdata),
    .tvalid (tx_axis_tvalid),
    .tready (tx_axis_tready),
    .tlast  (tx_axis_tlast),
    .tuser  (tx_axis_tuser)
);

bind gem_mac gem_axis_sva #(
    .PORT_NAME  ("rx_axis"),
    .USER_WIDTH (1)
) u_rx_axis_sva (
    .clk    (tx_clk),          // sys_clk = tx_clk for v1 (B.7 item 3)
    .rst_n  (tx_rst_n),
    .tdata  (rx_axis_tdata),
    .tvalid (rx_axis_tvalid),
    .tready (rx_axis_tready),
    .tlast  (rx_axis_tlast),
    .tuser  (rx_axis_tuser)
);

`endif
