//----------------------------------------------------------------------------
// gem_axis_sva -- AXI-Stream protocol legality, bound to both user ports.
//
// A test checks a scenario you constructed. An assertion checks an invariant
// during EVERY scenario, including the ones nobody thought to write. These
// five properties hold on every cycle of every regression run, which means the
// random sweeps are checking protocol legality for free.
//
// Bound rather than instantiated, so no property language ever appears in
// synthesisable code (fpga_project_flow.md Stage 3). The bind statements live
// at the bottom of this file, which also makes them one place to look when
// asking "what is actually being checked".
//
// These are also the interface contract in executable form. When Stage 5
// connects a module that deasserts tvalid mid-transfer because its author read
// the handshake differently, this fires at the exact cycle it happens rather
// than surfacing as corrupted output forty thousand cycles later.
//----------------------------------------------------------------------------

`ifndef GEM_AXIS_SVA_SV
`define GEM_AXIS_SVA_SV

`timescale 1ns / 1ps

module gem_axis_sva #(
    parameter string PORT_NAME = "axis",
    parameter int    USER_WIDTH = 1
) (
    input wire                    clk,
    input wire                    rst_n,
    input wire [7:0]              tdata,
    input wire                    tvalid,
    input wire                    tready,
    input wire                    tlast,
    input wire [USER_WIDTH-1:0]   tuser
);

    // Every property is guarded against reset: a port is allowed to be
    // anything while held in reset, and asserting otherwise produces the
    // classic wall of startup failures that trains people to ignore assertion
    // output entirely.
    //
    // The guard is repeated per property rather than written once as
    // `default disable iff (!rst_n)`, which XSim 2024.2 rejects outright:
    // "the SystemVerilog feature Default Disable iff declaration is not
    // supported yet for simulation". Same meaning, more typing.

    // 1. Once offered, a beat stays offered. A master that withdraws tvalid
    //    because it changed its mind has broken the handshake, and the symptom
    //    downstream is a dropped byte with no other trace.
    a_tvalid_held: assert property (@(posedge clk) disable iff (!rst_n)
        (tvalid && !tready) |=> tvalid)
        else $error("%s: tvalid deasserted before tready -- beat withdrawn", PORT_NAME);

    // 2. The payload of a stalled beat cannot change underneath the receiver.
    a_tdata_stable: assert property (@(posedge clk) disable iff (!rst_n)
        (tvalid && !tready) |=> $stable(tdata))
        else $error("%s: tdata changed while the beat was stalled", PORT_NAME);

    a_tlast_stable: assert property (@(posedge clk) disable iff (!rst_n)
        (tvalid && !tready) |=> $stable(tlast))
        else $error("%s: tlast changed while the beat was stalled", PORT_NAME);

    // 3. tuser is a per-frame sideband, so it must also survive a stall.
    a_tuser_stable: assert property (@(posedge clk) disable iff (!rst_n)
        (tvalid && !tready) |=> $stable(tuser))
        else $error("%s: tuser changed while the beat was stalled", PORT_NAME);

    // 4. tlast is meaningless without a beat to end. This catches an end-of-
    //    frame pulse generated by a frame counter rather than by the datapath,
    //    which is a real and easy mistake.
    a_tlast_needs_tvalid: assert property (@(posedge clk) disable iff (!rst_n)
        tlast |-> tvalid)
        else $error("%s: tlast asserted without tvalid", PORT_NAME);

    // 5. Nothing may be driven X once out of reset. X propagation reads
    //    exactly like a wrong value in a log file and is not the same thing.
    a_no_x: assert property (@(posedge clk) disable iff (!rst_n)
        tvalid |-> !$isunknown({tdata, tlast, tuser}))
        else $error("%s: X or Z on the data path during a valid beat", PORT_NAME);

endmodule


//----------------------------------------------------------------------------
// Binds. Both user ports of gem_mac get the same contract -- which is the
// point of using a standard interface in the first place.
//----------------------------------------------------------------------------

bind gem_mac gem_axis_sva #(
    .PORT_NAME  ("tx_axis"),
    .USER_WIDTH (112)
) u_tx_axis_sva (
    .clk    (tx_clk),
    .rst_n  (tx_rst_n),
    .tdata  (tx_axis_tdata),
    .tvalid (tx_axis_tvalid),
    .tready (tx_axis_tready),
    .tlast  (tx_axis_tlast),
    .tuser  (tx_axis_tuser)
);

bind gem_mac gem_axis_sva #(
    .PORT_NAME  ("rx_axis"),
    .USER_WIDTH (1)
) u_rx_axis_sva (
    .clk    (tx_clk),          // sys_clk = tx_clk for v1 (B.7 item 3)
    .rst_n  (tx_rst_n),
    .tdata  (rx_axis_tdata),
    .tvalid (rx_axis_tvalid),
    .tready (rx_axis_tready),
    .tlast  (rx_axis_tlast),
    .tuser  (rx_axis_tuser)
);

`endif
