//----------------------------------------------------------------------------
// tb_gem_uart_tx -- decode the transmitter's own output with a receiver that
// has never heard of its divider.
//
// THE POINT OF THIS TEST IS THE INDEPENDENCE, not the decoding. A receiver
// built from the DUT's own CLKS_PER_BIT would agree with any divisor,
// including a wrong one: both sides would be off by the same factor and every
// octet would arrive intact. So the receiver here computes its bit period from
// the baud rate as a duration -- 1e9 / 115200 nanoseconds -- and samples in
// the middle of each bit. If the design's integer division of 125 MHz lands
// somewhere it should not, the sampling points walk off the bits and this test
// fails, which is the entire reason it exists.
//
// It also runs at the real parameters rather than a shortened divisor. A
// 10-bit frame at 115200 is 86.8 us and eight of them are under a millisecond
// of simulation, which is cheap enough that there is no reason to check a baud
// rate the design does not ship with.
//
// WHAT IS CHECKED:
//   * every octet decodes to the octet that was offered, LSB first
//   * the start bit is low and the stop bit is high -- a frame that loses its
//     stop bit still decodes correctly in most receivers and then desynchronises
//     the next one, which is why it is checked rather than assumed
//   * the measured bit period matches 115200 baud within 2%, the usual budget
//     before a receiver's mid-bit sample walks into the neighbouring bit
//   * the line idles high, including before the first octet and after the last
//   * `ready` is low for the whole frame and back-to-back octets stream with
//     `valid` simply held high
//----------------------------------------------------------------------------

`timescale 1ns / 1ps

`include "gem_mac_params.vh"

module tb_gem_uart_tx;

    import gem_tb_pkg::*;

    // 8 ns, and stated here rather than derived from the design so that the
    // duration arithmetic below has an independent basis.
    localparam real CLK_HALF_NS = 4.0;

    // The specification's bit period, in nanoseconds. Nothing in this file may
    // use CLKS_PER_BIT to work this out.
    localparam real BIT_NS = 1_000_000_000.0 / real'(`GEM_UART_BAUD);

    // What a UART receiver typically tolerates before the stop bit's mid-point
    // has drifted into the next frame's start bit.
    localparam real BAUD_TOLERANCE = 0.02;

    logic       clk = 1'b0;
    logic       rst_n = 1'b0;
    logic [7:0] data = 8'h00;
    logic       valid = 1'b0;
    wire        ready;
    wire        tx;

    gem_uart_tx u_dut (
        .clk   (clk),
        .rst_n (rst_n),
        .data  (data),
        .valid (valid),
        .ready (ready),
        .tx    (tx)
    );

    always #(CLK_HALF_NS * 1ns) clk = ~clk;

    //----------------------------------------------------------------------
    // The independent receiver.
    //
    // Mid-bit sampling, timed from the falling edge that starts a frame: the
    // start bit's centre is half a period in, so data bit k sits at
    // (1.5 + k) periods and the stop bit at 9.5.
    //----------------------------------------------------------------------
    logic [7:0] rx_queue [$];
    real        measured_bit_ns [$];
    int         rx_count = 0;

    //----------------------------------------------------------------------
    // Bit-period measurement, taken from the DESIGN'S edges.
    //
    // The first version of this test computed the period from the receiver's
    // own sampling times, which are generated by its own delay loop -- so the
    // arithmetic came back as exactly one bit period no matter what the design
    // did, and a planted 3.2% divisor error passed. Framing alone cannot catch
    // that either: a receiver resynchronises on every start bit, so a few
    // percent of error is still decoding correctly nine bits later. That is
    // precisely why a real UART tolerates it, and precisely why a test that
    // only decodes proves nothing about the baud rate.
    //
    // What is measured instead is the width of the low run that begins each
    // frame, which is made of the design's own two edges. Its length in bit
    // periods is known from the decoded octet: the start bit, plus however
    // many of the data bits are zero from the LSB up, since those are
    // transmitted first and are indistinguishable from the start bit on the
    // wire. 0x00 therefore gives a nine-period run to measure -- which is the
    // reason it is in the octet list.
    //----------------------------------------------------------------------
    real first_fall_ns = -1.0;
    real first_low_ns [$];
    bit  awaiting_first_rise = 1'b0;

    always @(negedge tx) begin
        if (awaiting_first_rise) first_fall_ns = $realtime;
    end

    always @(posedge tx) begin
        if (awaiting_first_rise && first_fall_ns >= 0.0) begin
            first_low_ns.push_back($realtime - first_fall_ns);
            awaiting_first_rise = 1'b0;
        end
    end

    // Bit periods in the low run that opens a frame: the start bit, plus the
    // zeros the octet begins with, LSB first.
    function automatic int low_periods(input logic [7:0] octet);
        int n = 1;
        int k;
        for (k = 0; k < 8; k++) begin
            if (octet[k] === 1'b0) n++;
            else break;
        end
        return n;
    endfunction

    task automatic receive_forever();
        logic [7:0] octet;
        real        t_start, t_stop;
        int         k;
        forever begin
            // Armed before the edge is awaited so the monitor above and this
            // task agree about which low run belongs to which frame.
            awaiting_first_rise = 1'b1;
            first_fall_ns = -1.0;
            @(negedge tx);
            t_start = $realtime;

            // Centre of the start bit: it must still be low here, or that
            // falling edge was a glitch rather than a frame.
            #(0.5 * BIT_NS * 1ns);
            note_check();
            if (tx !== 1'b0) begin
                report_fail("gem_uart_tx",
                    "the line rose again before the centre of the start bit -- that was not a frame");
            end

            for (k = 0; k < 8; k++) begin
                #(BIT_NS * 1ns);
                octet[k] = tx;          // LSB first
            end

            #(BIT_NS * 1ns);
            note_check();
            if (tx !== 1'b1) begin
                report_fail("gem_uart_tx", $sformatf(
                    "stop bit of octet 0x%02h is low -- framing is wrong even though the data decoded",
                    octet));
            end
            t_stop = $realtime;
            rx_queue.push_back(octet);
            rx_count++;
        end
    endtask

    //----------------------------------------------------------------------
    // Stimulus
    //----------------------------------------------------------------------
    task automatic send(input logic [7:0] octet);
        @(posedge clk);
        data  <= octet;
        valid <= 1'b1;
        // Held until the transmitter takes it; this is also what proves the
        // handshake works with valid simply parked high.
        @(posedge clk);
        while (!ready) @(posedge clk);
        wait (ready == 1'b0);
    endtask

    localparam int N_OCTETS = 8;

    // Deliberately including 0x00 and 0xFF: the all-zeros octet is the one a
    // broken start-bit boundary swallows, and the all-ones octet is the one
    // that looks identical to an idle line.
    logic [7:0] to_send [N_OCTETS] = '{8'h47, 8'h00, 8'hFF, 8'h55, 8'hAA, 8'h01, 8'h80, 8'h0A};

    int  i;
    real avg_bit_ns;
    bit  ok;

    initial begin
        begin_scenario("gem_uart_tx");

        fork
            receive_forever();
        join_none

        repeat (4) @(posedge clk);

        note_check();
        if (tx !== 1'b1) begin
            report_fail("gem_uart_tx", "the line does not idle high out of reset");
        end

        rst_n = 1'b1;
        repeat (4) @(posedge clk);

        note_check();
        if (ready !== 1'b1) begin
            report_fail("gem_uart_tx", "the transmitter is not ready when idle");
        end

        for (i = 0; i < N_OCTETS; i++) begin
            send(to_send[i]);

            note_check();
            if (ready !== 1'b0) begin
                report_fail("gem_uart_tx", $sformatf(
                    "ready stayed high after octet %0d was accepted -- a second octet would overwrite the frame in flight", i));
            end
        end

        // Let the last frame finish, plus a margin of a full frame.
        valid <= 1'b0;
        #(11 * BIT_NS * 1ns);

        note_check();
        if (rx_count != N_OCTETS) begin
            report_fail("gem_uart_tx", $sformatf(
                "decoded %0d octets, expected %0d", rx_count, N_OCTETS));
        end

        for (i = 0; i < rx_count && i < N_OCTETS; i++) begin
            note_check();
            if (rx_queue[i] !== to_send[i]) begin
                report_fail("gem_uart_tx", $sformatf(
                    "octet %0d decoded as 0x%02h, sent 0x%02h", i, rx_queue[i], to_send[i]));
            end
        end

        // One period measurement per frame, each from that frame's own two
        // edges and divided by the number of bit periods the decoded octet
        // says that low run contains.
        note_check();
        if (first_low_ns.size() != rx_count) begin
            report_fail("gem_uart_tx", $sformatf(
                "captured %0d start-bit low runs for %0d decoded octets -- the measurement is not paired with the frames",
                first_low_ns.size(), rx_count));
        end

        avg_bit_ns = 0.0;
        for (i = 0; i < first_low_ns.size() && i < rx_count; i++) begin
            measured_bit_ns.push_back(first_low_ns[i] / real'(low_periods(rx_queue[i])));
            avg_bit_ns += measured_bit_ns[i];
        end
        if (measured_bit_ns.size() > 0) begin
            avg_bit_ns = avg_bit_ns / real'(measured_bit_ns.size());
        end

        note_check();
        if (avg_bit_ns < BIT_NS * (1.0 - BAUD_TOLERANCE) ||
            avg_bit_ns > BIT_NS * (1.0 + BAUD_TOLERANCE)) begin
            report_fail("gem_uart_tx", $sformatf(
                "measured bit period %0.1f ns against %0.1f ns for %0d baud (%0.2f%% off, tolerance %0.0f%%)",
                avg_bit_ns, BIT_NS, `GEM_UART_BAUD,
                100.0 * (avg_bit_ns - BIT_NS) / BIT_NS, 100.0 * BAUD_TOLERANCE));
        end

        note_check();
        if (tx !== 1'b1) begin
            report_fail("gem_uart_tx", "the line does not return to idle high after the last frame");
        end

        $display("[gem_tb] gem_uart_tx: %0d octets, measured bit period %0.1f ns against %0.1f ns ideal (%0.3f%%)",
                 rx_count, avg_bit_ns, BIT_NS, 100.0 * (avg_bit_ns - BIT_NS) / BIT_NS);

        ok = check_done();
        if (!ok) $fatal(1, "[gem_tb] gem_uart_tx FAILED");
        $finish;
    end

    initial begin
        #20ms;
        $fatal(1, "[gem_tb] gem_uart_tx TIMED OUT");
    end

endmodule
